Updated Prim's MST
admu-progvar/progvar-library pull request #11
Opened 2022-03-11 21:05 UTC by rap2montemayor

Basically doing everything that was asked for in https://github.com/admu-progvar/progvar-library/issues/6
- Wrote a "not abridged" version in `pvl/graphs/mst/prim.hpp`
- Placed new code in `pvl/abridged/graphs/mst/prim.cpp`
- Added tests to `tests/graphs/mst/prim.cc`

2022-03-14 15:35 UTC, leloykun commented on tests/graphs/CMakeLists.txt
> +include_directories(mst)
[nit] add a new line

2022-03-14 15:40 UTC, leloykun commented on pvl/abridged/graphs/mst/prim.cpp
> +}
[nit] compress into a single line

we use the stuff in `pvl/abridged/` to generate the team notebooks so they need to be as short as possible

2022-03-14 15:53 UTC, leloykun requested changes
update the contributor's section in the README

2022-03-20 08:25 UTC, rap2montemayor commented
Added all the requested changes. Should be ready to merge pull request.

2022-03-20 08:30 UTC, leloykun approved these changes

2022-03-20 09:01 UTC, merged