pass team name as argument
admu-progvar/progvar-library pull request #21
Opened 2022-03-23 17:41 UTC by bullybutcher

2022-03-23 19:12 UTC, leloykun requested changes

2022-03-23 19:12 UTC, leloykun commented on notebook/notebook.tex
> +  \title{$KFC$}
set the default team name to `Ateneo ProgVar`

2022-03-24 04:52 UTC, bullybutcher commented on notebook/makefile.sh
> +pdflatex -shell-escape "\def\ICPCCONFIG{1} \def\team{$teamname} \input{notebook.tex}"
i think underscore `_` in latex is a reserved character

2022-03-24 18:01 UTC, leloykun commented on notebook/makefile.sh
> +pdflatex -shell-escape "\def\ICPCCONFIG{1} \def\team{$teamname} \input{notebook.tex}"
ah, nvm, let's just use `TEAMNAME` then

2022-03-26 00:45 UTC, leloykun approved these changes

2022-03-29 17:04 UTC, leloykun commented
@bullybutcher , I'm just gonna merge this since it's been 6 days since I approved it

2022-03-29 17:04 UTC, merged